app/views/items/_footer.html.haml
app/views/items/_header.html.haml
app/views/items/_main.html.haml

aタグの記述から、link_toへの変更
link_toへの変更することにより、今後の仕様変更及び非同期での送信に柔軟に対応できるため。

aタグからlink_toへの変更

---

app/assets/stylesheets/modules/_footer.scss
app/assets/stylesheets/modules/_main.scss
app/views/items/_footer.html.haml
app/views/items/_header.html.haml

haml/css を本番環境用に編集した
png.jpg共に本番環境で表示させるため

本番環境での画像の表示2

---

README.md

マークダウンが適用されるようにした
マークダウンが適用されず、見辛くなってしまっていたため

READE.mdの修正

---

app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.haml

deviseのサーバーサイド実装をし、テーブルに登録できるようにする

devise サーバー1

---

app/views/items/_header.html.haml
db/schema.rb

ログアウト機能の実装
新規登録後、ログアウトできなかったため、簡易的にログアウト機能を実装

ログアウト機能 実装1

---

db/schema.rb

usersテーブルのaddressとhouse_numberのカラムを削除
新規登録を実現するため

mysql　カラムの編集

---

app/assets/stylesheets/modules/_header.scss
app/views/items/_header.html.haml
config/routes.rb

if文を使用し、サインインとサインアウト時で、トップページのヘッダー内にある項目を切り替える

トップページ　login/logout切り替え

---

db/migrate/20200415151153_add_address_to_users.rb
db/migrate/20200415152659_change_column_building_null.rb
db/schema.rb

マイグレーションファイルの修正ファイルを作成
usersテーブルのaddressにreferencesを追加
addressesテーブルのbuildingのNOTNULL制約の削除
address_idを付与しaddressesテーブルと紐付けするため

マイグレーションファイルの修正

---

app/assets/stylesheets/login.scss
app/views/devise/sessions/new.html.haml

白石さんに作成して頂いたログインビューのデザインをupdate

ログインビューのデザイン修正1

---

app/controllers/users/registrations_controller.rb
app/views/credit_cards/index.html.haml
app/views/devise/registrations/new_credit_cards.haml
config/routes.rb
db/migrate/20200416141034_add_birthday_to_user.rb

what
新規登録→住所登録→カード登録→完了しました
この順番で実装しました。
今回は、カードの情報が上手く保存できなかったです
原因が @user = User.new(session["devise.regist_data"]["user"])
　　  @address = Address.new(session["devise.regist_data"]["address"])
　　　 @user.save
この記述をdef create_credit_cardsに入れていたことです。
userを新しく作っているので、２つあるよ？なんで？
と言われていた。
why
新規登録を分けてあげることでuserに
登録が複雑じゃないと伝わる
ユーザーは重要事項をしっかりかける
エラーを減らすことができる

ウィザード形式の登録ができました

---

app/assets/stylesheets/registrations_addresses.scss
app/models/user.rb
app/views/devise/registrations/new_address.html.haml
db/migrate/20200420112629_change_postal_code_to_adresses.rb
db/migrate/20200420120941＿hoge.rb
db/schema.rb

住所登録の都道府県の項目を
enumを用いてプルダウン式に実装
47都道府県以外を入力できないようにするため
入力ミスを防ぐため

都道府県のプルダウン実装

---

app/views/items/new.html.haml
db/schema.rb

商品登録のhaml
category_nameからnameに変更
DBとのカラム名を一致させるため

修正:商品登録のカテゴリー

---

Gemfile
Gemfile.lock
app/controllers/items_controller.rb
app/models/item.rb
app/views/items/new.html.haml
config/environments/development.rb
config/storage.yml

mini_magickのgemを導入し
画像が投稿出来るように実装
本番環境で画像投稿を可能にするため

修正:active_stotrageの画像登録

---

app/views/items/new.html.haml

テスト:マージの取り消し

---

app/views/items/new.html.haml

item-editting商品修正 (new.html.haml)

---

app/assets/stylesheets/categories/index.scss
app/controllers/items_controller.rb
app/validators/my_validator.rb
app/views/categories/index.html.haml

1. カテゴリーのview崩れの修正
2. カスタムバリデーションの修正
1. カテゴリー一覧の背景色の変更により、カテゴリー選択時の識別が容易になるため
2. item newアクション時にエラーが発生していたため解消

category view 修正

---

app/assets/stylesheets/credit_cards/card_new.scss
app/controllers/items_controller.rb
app/views/credit_cards/new.html.haml
app/views/items/show.html.haml

1. 商品購入時、カード登録ができていないと購入できないように実装
2. 商品詳細ページのカテゴリーのリンクを記述
商品購入時のエラー解消のため

クレジットカード未登録時のハンドリング

---

app/views/items/_footer.html.haml

WHAT
トップページから出品ページに飛べるようリンクを作成
①ログインしているユーザーは出品ページへ
②ログインしていないユーザーはログインページへ

出品ページへのルート設定

---

app/assets/stylesheets/items/purchase.scss
app/validators/my_validator.rb
app/views/items/_footer.html.haml
app/views/items/purchase_edit.html.haml

what
価格の位置を直した！
全体が右に偏っていたので修正しました
why
使う側が少しでもみやすいように！

商品購入完了画面のviewを修正

---

app/assets/stylesheets/items/purchase.scss
app/views/items/purchase_edit.html.haml
app/views/items/purchase_index.html.haml

商品確認の文字が大きくなって、view崩れが起きていたので
直しました！

購入画面のviewを綺麗にした

---

app/assets/stylesheets/items/new.scss

scssの修正し、ウィンドウサイズを変更しても常にフォームが中心にあるように変更した

商品出品のview修正

---

app/assets/stylesheets/items/purchase.scss
app/views/items/purchase_edit.html.haml
app/views/items/purchase_index.html.haml

リファクラリング,ビュー崩れの修正

---

app/assets/stylesheets/items/purchase.scss
app/views/items/purchase_edit.html.haml
app/views/items/purchase_index.html.haml

商品購入画面のビュー崩れの修正
画像の配置変更を実施し、購入者が購入商品の確認がし易く実装

リファクタリング,ビュー崩れの修正

---

app/models/item.rb
app/validators/my_validator.rb
app/validators/price_validator.rb

カテゴリーのバリデーションの再設定
priceバリデーション設定時にCategoryバリデーションが効かなくなっていたため修正

カスタムバリデーションの再設定

---

app/models/item.rb
app/validators/my_validator.rb
app/validators/price_validator.rb

'gem 'validates_email_format_of' install 
To eliminate errors during credit card registration

Email Address validation changes
